### ISSUE TITLE
When Metric data collection plugin execution times out, all metric data didn't collect.

### ISSUE THREAD

**Issue by hsksyusk** [heartbeatsjp/happo-agent#35]
- version: 0.99
- issue :
    - When Metric data collection plugin execution times out, all metric data didn't collect.
        - Execution timeout occurs on Happo side, not on the plugin side. (no response from the plugin) 
        - Error log:

            ```
            2017/12/14 22:02:41 Exec timeout: <plugin execution command>
            ```

        - Metric data didn't collect for other plugins.

**Comment by netmarkjp** [comment]
Thanks for reporing.

As you say, one plugin blocks all metrics is not good behavior.
I did PR https://github.com/heartbeatsjp/happo-agent/pull/47 and this change will contain in next release.
